### PR TITLE
Merge pull request #1 from shiftcodeYT/master

### PR DESCRIPTION
**Pull request by FallenDev**
Pull

### CODE REVIEW

**Comment by FallenDev** [comment]
Pull

**Comment by shiftcodeYT** [comment]
what did you change?

**Comment by FallenDev** [comment]
Nothing, was pulling from you, but it was dumb and did it reverse. Ha!

**Comment by shiftcodeYT** [comment]
;D

**Comment by FallenDev** [comment]
I cancelled it. The idea of a pull I'm trying to pull your data to update the files I have. Not sure why it was pushing instead of pulling. After I get home I should have the UI almost done. I'll just need to connect everything. Should be set for tomorrow.

**Comment by shiftcodeYT** [comment]
ok :)

**Pull request closed without merging**
